# Generated by Django 5.2.7 on 2025-11-07 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facturaitem_budget_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetline',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
