# Generated by Django 5.2.7 on 2025-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_budgetline_created_at_budgetline_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50, unique=True)),
                ('descriere', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eco_coduri',
            },
        ),
    ]
