# Generated by Django 5.2.7 on 2025-11-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ecocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracte',
            name='linie_bugetara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracte', to='core.budgetline'),
        ),
        migrations.AlterField(
            model_name='contracte',
            name='eco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ecocode'),
        ),
    ]
