# Generated by Django 5.2.7 on 2025-11-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contracte_linie_bugetara_alter_contracte_eco'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='contract_is_planned',
            field=models.BooleanField(default=True, verbose_name='Contractul este planificat?'),
        ),
    ]
