# Generated by Django 5.2.7 on 2025-11-27 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_factura_contract_is_planned'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='eco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturi_neprogramate', to='core.ecocode'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturi', to='core.contracte'),
        ),
    ]
