# Generated by Django 5.2.7 on 2026-10-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_factura_eco_alter_factura_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodBugetar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_bugetar', models.CharField(max_length=50)),
                ('denumirea', models.TextField()),
            ],
            options={
                'verbose_name': 'Cod bugetar',
                'verbose_name_plural': 'Coduri bugetare',
                'db_table': 'CoduriBugetare',
            },
        ),
        migrations.CreateModel(
            name='LinieBugetara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_academic', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('comanda_de_stat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('venituri_colectate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_cheltuieli', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'LiniiBugetare',
            },
        ),        
        migrations.CreateModel(
            name='LiniaBugetaraCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comanda_de_stat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('venituri_colectate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_cheltuieli', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cod_bugetar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calcule', to='core.codbugetar')),
                ('linia_bugetara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calcule', to='core.liniebugetara')),
            ],
            options={
                'db_table': 'LiniaBugetara_Calc',
            },
        ),
    ]
